project_id = "ccyyxkjpgebjnstevgkw"

[functions.delete-expired-messages]
verify_jwt = true

[functions.publish-scheduled-posts]
verify_jwt = true

[functions.posts]
verify_jwt = true

[functions.reactions]
verify_jwt = true

[functions.messages]
verify_jwt = true

[functions.messages-v2]
verify_jwt = true

[functions.friendships]
verify_jwt = true

[functions.profiles]
verify_jwt = true

[functions.auth-settings]
verify_jwt = false

[functions.create-verification-checkout]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false

[functions.send-signup-otp]
verify_jwt = false

[functions.verify-signup-otp]
verify_jwt = false

[functions.create-official-account]
verify_jwt = true

[functions.process-tip]
verify_jwt = true

[functions.publish-scheduled-posts]
verify_jwt = false

[functions.create-coins-checkout]
verify_jwt = true
